#!/usr/bin/env python
from pathlib import Path
import sys

import fountain


def import_custom_wordlist() -> tuple[str]:
	"""Check for a custom wordlist."""
	path = sys.argv[1]
	return fountain.file_io.read(path)


if __name__ == "__main__":

	if not fountain.has_all_static_data():
		fountain.generate_data()

	if len(sys.argv) > 1:
		custom_wordlist = import_custom_wordlist()
