#!/usr/bin/env python
from pathlib import Path
import sys

import fountain


def get_path():
	"""Return a custom or default path."""
	try:
		return sys.argv[1]
	except IndexError:
		return 'wordlist.txt'


if __name__ == "__main__":
	
	path = get_path()

	WORDLIST = fountain.io.get_wordlist(path)
